spring:
  application:
    name: command-service
  main:
    allow-bean-definition-overriding: true
  profiles:
    active:
      - alone
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mydb
    username: sdc
    password: '@sdc.com'
    hikari:
      maximum-pool-size: 50
      minimum-idle: 5
    type: com.zaxxer.hikari.HikariDataSource
    driverClassName: net.sf.log4jdbc.sql.jdbcapi.DriverSpy

  jpa:
    hibernate:
      ddl-auto: update

    properties:
      hibernate:
#        jpa 관련 log 표시
        show_sql: true
        format_sql: true

server:
  port: 9002


eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka

management:
  endpoints:
    web:
      exposure:
        include: refresh, health, beans, busrefresh, info, prometheus, metrics

#
#logging:
#  level:
#    root: info